### ISSUE TITLE
can't open popup window in views examples

### ISSUE THREAD

**Issue by tiagovignatti** [01org/ozone-wayland#202]
steps to reproduce:

1. compile 'views_examples_with_content_exe' target
2. open Weston with 'WAYLAND_DEBUG=1 ./src/weston 2>&1| grep popup'
3. open views examples running './views_examples_with_content_exe --no-sandbox'
4. click in the bar at the top of the window where it says "Bubble"
5. a popup window was supposed to open now with a dropdown style of menu and several options
6. in Weston's output, you will see a popup_done event being erroneously sent for closing the popup window that was supposed to open.

My hunch of the problem is that there's still some input event that is about to process in the toplevel surface just after the popup is opened. That would cause Weston scenegraph to think that actually the toplevel surface is becoming activated again and send a popup_done for the newly created surface to be destroyed.

This all works on Aura X11/Linux.

**Comment by kalyankondapally** [comment]
Works with master.
