### ISSUE TITLE
Update XDG-Shell to 1.6.0

### ISSUE THREAD

**Issue by Tarnyko** [01org/ozone-wayland#317]
Hello, as Weston 1.6.0 was released some time ago, and it unsurprisingly broke XDG-Shell, I plan to update the XDG-Shell-related code in Ozone-Wayland.

Related features are : minimization, focus restore on unminization.

Under Tizen, we do not need to have a backwards compatibility option with Weston 1.5.0 ; the whole world may disagree, though. Is backwards compatibility with Weston 1.5.0 wanted ?
Drawbacks are : lots more of #ifdefs and additional source files.

**Comment by kalyankondapally** [comment]
Merged
