### ISSUE TITLE
windowDeactivate event doesn't work

### ISSUE THREAD

**Issue by joone** [01org/ozone-wayland#346]
Recently, we added support for windowActivate/Deactivate event handlers(https://github.com/01org/ozone-wayland/commit/afaf5500567d87a9eef8e29267bf1654f358586c, https://github.com/01org/ozone-wayland/commit/3667f43f1284c3764461306fbcbd830eb5ff06bc), but windowDeactivate doesn't work.

**Comment by kalyankondapally** [comment]
Merged
