### ISSUE TITLE
[Tizen] Build break related to libva

### ISSUE THREAD

**Issue by joone** [01org/ozone-wayland#348]
In file included from obj/content/content_common.gen/va_stubs.cc:18:0:
../../third_party/libva/va/va_x11.h:28:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.
[22/1157] CXX obj/content/common/content_common.plugin_list.o
ninja: build stopped: subcommand failed.

**Comment by joone** [comment]
Is this related to https://codereview.chromium.org/825163004 ?

**Comment by joone** [comment]
https://codereview.chromium.org/817023005/diff/40001/content/common/BUILD.gn

This change may cause the build break.

**Comment by rakuco** [comment]
The entire CL is the problem: the action to generate the stubs in `content_common.gypi` isn't run only when `use_x11=1` anymore, so even though we kind of duplicate it in `ozone/media/video.gypi`, we still run the version in content_common with a `va_stub_header.fragment` that includes X11 headers.

@kalyankondapally, given it was Lionel who wrote that CL are you familiar with the reasoning behind the it and whether there's a way to accommodate both its needs and oz-wl's?

**Comment by kalyankondapally** [comment]
This should be resolved.
