### ISSUE TITLE
MileStone-Carnival

### ISSUE THREAD

**Issue by kalyankondapally** [01org/ozone-wayland#361]
TODO:
1)Release notes.
2)Source release and test every thing works properly with appropriate Chromium release.

**Comment by kalyankondapally** [comment]
@rakuco We want to come up with some good names for the Milestones

Usual commits:
1)https://github.com/01org/ozone-wayland/commit/a005357c9386c6c0030cb83e885234fc0f263da0
2)https://github.com/01org/ozone-wayland/commit/be1710d367ae8794e45af3ef9621b2259490a997
3)https://github.com/01org/ozone-wayland/commit/3b101e471ded02ab5ab7360a7b48ec76de1d080b

**Comment by rakuco** [comment]
> @rakuco We want to come up with some good names for the Milestones

Given I'm currently in Brazil at the moment, Milestone-Carnival is the first one that comes to mind ;-)

**Comment by kalyankondapally** [comment]
Updated :)

**Comment by rakuco** [comment]
M41 was finally promoted to beta at the end of last week. Should we first move master forward a bit and then branch Carnival?
I'm asking because for 41.0.2272.16 (as well as M42/master) `0005-Media-Build-VaapiPictureWayland-as-part-of-Media.patch` needs to be rebased and integrated with https://codereview.chromium.org/860163003 and `0013-Temp-Patch-BuildFix-on-Non-ChromeOS-platforms.patch` should be replaced by https://codereview.chromium.org/812613004 + https://codereview.chromium.org/841113004.

**Comment by kalyankondapally** [comment]
rakuco, Ya should be fine. Have you already done that or do you want me to do it ?

**Comment by rakuco** [comment]
I can do it, but actually testing a full Chromium master build will take me several hours. We can take a leap of faith and just do it :)

**Comment by kalyankondapally** [comment]
I can test the chromium bits when you send the pull request. It will be 1 hr delay unfortunately :( How ever you can continue working on the release branch assuming those patches will be merged

**Comment by rakuco** [comment]
I've started committing to https://github.com/rakuco/ozone-wayland/commits/Milestone-Carnival
Please take a look at the changes there; the release notes are empty because I don't know what to add, and I've updated some patches in `patches/`.

**Comment by rakuco** [comment]
I think everything's ready in my branch except for the release date. Shall we proceed?

**Comment by kalyankondapally** [comment]
@rakuco sorry, missed this. Ya, pls push the release branch. Add the date to be the same day you are pushing it. Also you know you can tag the release in github right, we should also do that.

**Comment by kalyankondapally** [comment]
@rakuco planning to push the branch ?

**Comment by rakuco** [comment]
Sorry, I wasn't working last Friday and Monday. I've pushed the Milestone-Carnival branch and tagged it.
