### ISSUE TITLE
Release public builds every milestone

### ISSUE THREAD

**Issue by darkcoconuts** [01org/ozone-wayland#364]
I know that myself and many other people are looking to try out chromium on wayland, but building this project is really time consuming and could be difficult. It would be really great if there were publicly available builds like the valentines release form last year that intel put together.

**Comment by antokara** [comment]
+1 for a package for Fedora Gnome on Wayland, which could really help the tests...

**Comment by kalyankondapally** [comment]
sorry for the delay. The idea was package maintainers for a particular distribution would be able to do this and we give any needed support. If you guys see any thing which is causing issues to build this project, I am more than happy to help and see what we can do it ease the stuff.

**Comment by kalyankondapally** [comment]
Closing this. We have added all needed build instructions in ReadME file and preliminary instructions for people interested in packaging this for particular distributions here https://github.com/01org/ozone-wayland/wiki/Packaging. It would be nice to receive any feedback and if there is something we can do to ease things.
