### ISSUE TITLE
MileStone-Hood

### ISSUE THREAD

**Issue by kalyankondapally** [01org/ozone-wayland#373]
TODO:
1)Release notes.
2)Source release and test every thing works properly with appropriate Chromium release.

**Comment by kalyankondapally** [comment]
HWA Video needs to be disabled for this release as things have changed a lot upstream.

**Comment by kalyankondapally** [comment]
@rakuco https://github.com/01org/ozone-wayland/commits/Milestone-Hood 

This is based on M43. Some of the patches are not in Master as with latest Chromium, Media is broken in OZ-WL side. I will talk with JiaJia and see if she has time to fix the Media part. Once done master will get updated to latest Chromium. Luckily, these changes haven't entered M43 branch yet

**Comment by rakuco** [comment]
thank you.

@mrunalk: please use this branch in `DEPS.xwalk`.
