### ISSUE TITLE
M44 based release

### ISSUE THREAD

**Issue by kalyankondapally** [01org/ozone-wayland#374]
TODO:
1)Release notes.
2)Source release and test every thing works properly with appropriate Chromium release.

**Comment by rakuco** [comment]
any news here? is @joone going to come up with a name and branch master?

**Comment by joone** [comment]
@rakuco @kalyankondapally okay, I will do until this week.

**Comment by hobbitalastair** [comment]
@joone Any news on this?

**Comment by kalyankondapally** [comment]
@hobbitalastair its here https://github.com/01org/ozone-wayland/tree/Milestone-Jefferson

**Comment by rakuco** [comment]
Reopening; there are several commits in Milestone-Jefferson which actually do _not_ work with M44. 30cd769cc8709ebc1addf328265c31db3b4cc110 and d526b09391bfcf7144806b24d1a7e9e1893c35ac are broken, and #338 even updates the release scripts with an M45 version number. This all belongs in Milestone-Trask (#402).

**Comment by kalyankondapally** [comment]
@joone ping

@rakuco confused about #338

**Comment by rakuco** [comment]
Oops, I meant #383.

**Comment by hobbitalastair** [comment]
Should this bug be closed again?

**Comment by kalyankondapally** [comment]
@rakuco ?

**Comment by rakuco** [comment]
Oops, I thought my PR would've closed this issue automatically. I've now removed the Chromium-V45.0 tag that was pointing to an earlier M-Jefferson commit. The only thing the branch still needs is a `RELEASE-NOTES.txt`. If it's not necessary, then we can finally close it.

**Comment by kalyankondapally** [comment]
We need to fix that too @rakuco Can you push that ?

**Comment by rakuco** [comment]
I just don't know what to write :-) For example, I just used Debian sid's packages for the dependencies, and I'm not entirely sure what was new in this release.

**Comment by kalyankondapally** [comment]
We have usually included information like chromium revision, wayland/weston version this has been tested against and included issues fixed in Ozone-wayland. For Ozone-Wayland related changes, you can query for closed issues during this period i.e. https://github.com/01org/ozone-wayland/issues?q=milestone%3AJefferson+is%3Aclosed  which seems 0. I guess we can skip this part.

I will update it later today and close this.

**Comment by kalyankondapally** [comment]
Done
