### ISSUE TITLE
MileStone-Mazama

### ISSUE THREAD

**Issue by rakuco** [01org/ozone-wayland#375]
We need to create a branch tracking Chromium M42 (so far the support is still in the master branch).

TODO:
- [ ] Choose a name for the milestone
- [ ] Release notes
- [ ] Source release and test every thing works properly with appropriate Chromium release.

**Comment by rakuco** [comment]
+@joone, @kalyankondapally

**Comment by kalyankondapally** [comment]
Reg name: We where using the mountain names in Portland :) @Joone do you have anything in your list of names ?

**Comment by kalyankondapally** [comment]
Done https://github.com/01org/ozone-wayland/tree/Milestone-Mazama
