### ISSUE TITLE
Flaky visual corruption

### ISSUE THREAD

**Issue by hobbitalastair** [01org/ozone-wayland#387]
I've had a play with the Milestone-Jefferson now. However, on Weston (Intel G45 graphics) there is some mild image corruption evident, seemingly related to the titlebar. I haven't seen anything like it before, either in earlier releases that I've tried, or with xwayland clients.

![corruption](https://cloud.githubusercontent.com/assets/6619576/8610075/86e168de-2701-11e5-9417-e70632a6762c.png)
![corruption_2](https://cloud.githubusercontent.com/assets/6619576/8610078/9244a9fc-2701-11e5-8cd3-4955eab901d7.png)
![corruption_3](https://cloud.githubusercontent.com/assets/6619576/8610083/9a901bbe-2701-11e5-90e7-93ee7e8001a6.png)
![find_corruption](https://cloud.githubusercontent.com/assets/6619576/8610084/a174daf0-2701-11e5-91f4-b0842ae68a62.png)

The corruption appears to be related to the tab animations, although it has appeared elsewhere. I'm not sure what causes it.

I'd be happy to test out changes, although it takes a while for my machine to rebuild everything.

**Comment by kalyankondapally** [comment]
can u try out latest master and see if you can see this issue ?

**Comment by hobbitalastair** [comment]
Will do.

There will be a lag of a few days; I'm going to try to reproduce the libsecret issue first, then update the PKGBUILD.

**Comment by hobbitalastair** [comment]
I might also have a play around with less recent versions of the kernel/mesa/chromium-wayland to see whether that changes anything, although I haven't seen it with xwayland or wayland-terminal.

**Comment by hobbitalastair** [comment]
This is still an issue with not-quite-latest (yesterday's) master.

I haven't had a chance to play around with less recent versions of the kernel/mesa/chromium wayland, though, so it might not be a chromium-wayland issue.

**Comment by hobbitalastair** [comment]
This is *still* an issue, although the same caveat as above applies... hopefully I'll get around to this at some point.

**Comment by hobbitalastair** [comment]
Mesa regression between 10.3 and 10.6; I haven't investigated further.
Sorry for the noise!

**Comment by hobbitalastair** [comment]
As a note, there's this error in the logs for both my Milestone-Jefferson and Milestone-Trask builds:

    [2940:2940:0825/161104:ERROR:texture_manager.cc(1980)] [GroupMarkerNotSet(crbug.com/242999)!:D092BDA995130000]GL ERROR :GL_INVALID_VALUE : glTexImage2D: <- error from previous GL command

It *might* be related...

**Comment by kalyankondapally** [comment]
Hmm, ya. So, you are using Mesa 10.6. I can give it a try and see if I can replicate this. Let me know, mesa wayland and weston versions.

**Comment by hobbitalastair** [comment]
Mesa: 10.6.5
Wayland: 1.8.1
Weston: 1.8.0
