### ISSUE TITLE
Opening submenus does not work

### ISSUE THREAD

**Issue by hobbitalastair** [01org/ozone-wayland#388]
Opening submenus, for instance 'hamburger'->Bookmarks by either hovering over them or left clicking on them causes both menus to instantly vanish. This also occurs with folders on the bookmark bar (or did; I might have to check that again).

I can get them to display by holding down the right mouse button while hovering over the menu. However, they vanish if I release the right mouse button, so I can't left click...

One of the other members of the Arch forums also [reported the same issue](https://bbs.archlinux.org/viewtopic.php?pid=1505459#p1505459).

**Comment by kalyankondapally** [comment]
I am able to reproduce this pretty easily. Popups seem to be bit broken, looking into it.

**Comment by hobbitalastair** [comment]
Is this fixed by https://github.com/01org/ozone-wayland/commit/d49bc727229c82324978fbb70315c6fe2bd88368 as well?

**Comment by kalyankondapally** [comment]
Submenus can be opened now but they seem to not handle events.

**Comment by hobbitalastair** [comment]
Opening submenus now works, thanks!
