### ISSUE TITLE
Highlighting in multiple choice menus is in black

### ISSUE THREAD

**Issue by hobbitalastair** [01org/ozone-wayland#389]
This is a problem, because the text is also in black...
I tried two styles, which both had the same issue, but it could be caused by something other than ozone-wayland?

![drop_down](https://cloud.githubusercontent.com/assets/6619576/8610409/e099ebea-2705-11e5-9742-d98a00586e92.png)

On X11, the highlight in multiple choice menus is blue.

**Comment by kalyankondapally** [comment]
This could be due to some hardcoded internal style choices here: https://github.com/01org/ozone-wayland/blob/master/ui/webui/ozone_webui.cc, we choose black for fg, bg etc. Need to add proper support like with x11 variant.

**Comment by joone** [comment]
Here is a patch: https://github.com/01org/ozone-wayland/pull/408

**Comment by hobbitalastair** [comment]
@joone, @kalyankondapally: Is this fixed now?

**Comment by kalyankondapally** [comment]
Yes, should be.
