### ISSUE TITLE
Right click menus in "Bookmark Manager" vanish if I let go of the right mouse button

### ISSUE THREAD

**Issue by hobbitalastair** [01org/ozone-wayland#390]
Again; Milestone-Jefferson, Intel GPU, x86_64, Arch Linux, Weston.

Reproducing:
Open the bookmark manager page. Press the right mouse button to open a menu. Release the right mouse button; the menu will vanish.

What should happen:
The menu should stick around until I "click off" - left clicking elsewhere on the page works on Chromium on X11.

**Comment by kalyankondapally** [comment]
I am able to reproduce this pretty easily. Popups seem to be bit broken, looking into it.

**Comment by hobbitalastair** [comment]
Thanks!

Once I've figured out how to build from git master, I'll be happy to test any potential fixes.

**Comment by kalyankondapally** [comment]
I have a fix for this, will be pushing the changes to master soon.

**Comment by kalyankondapally** [comment]
Fix merged. Let me know if you still have these issues with master branch.
