### ISSUE TITLE
Tooltips appear at the top left corner of the window (?) and then flash

### ISSUE THREAD

**Issue by hobbitalastair** [01org/ozone-wayland#392]
Arch Linux x86_64, Weston, Milestone Jefferson.

If a tooltip appears, it will be at the top left corner of the window, and will 'flash'; instantly vanishing and then instantly reappearing. There's a slight lag, which might be related to the window close animation on Weston?

**Comment by kalyankondapally** [comment]
Did you check if the tooltip appears on x11 builds ? You need to hover your mouse over "new tab" or the bookmark button. It will come up with the purpose of that UI element.

**Comment by hobbitalastair** [comment]
The tooltip appears in the right place in both Chromium in xwayland, and Chromium on plain old X.

This was also an issue with earlier builds of Chromium with ozone-wayland, so I'm assuming that it is still a problem - I haven't figured out how to create a PKGBUILD that only downloads what it needs yet.

**Comment by hobbitalastair** [comment]
Tested - it appears to be fixed, thanks!
