### ISSUE TITLE
WindowManagerWayland should probably not trust input from GPU process

### ISSUE THREAD

**Issue by mcatanzaro** [01org/ozone-wayland#399]
In upstream Chromium, the browser process isn't supposed to trust input from the GPU process. An example of what not to do:

```
void WindowManagerWayland::OnWindowDeActivated(unsigned windowhandle) {
  DCHECK(windowhandle);
  ui::OzoneWaylandWindow* window = GetWindow(windowhandle);
  DCHECK(window);
  window->GetDelegate()->OnActivationChanged(false);
}
```

In this case, if a malicious GPU process sends 0 for `windowhandle`, then `window` will be null and the final line is a null pointer dereference in a release build. We should probably replace the `DCHECK`s with early returns?

I think this would be ideal:

```
void WindowManagerWayland::OnWindowDeActivated(unsigned windowhandle) {
  ui::OzoneWaylandWindow* window = GetWindow(windowhandle);
  if (!window)
    return;
  window->GetDelegate()->OnActivationChanged(false);
}
```

(The obvious disadvantage being that the nice development assert is gone....)

**Comment by kalyankondapally** [comment]
GPU process and Browser process are the trusted process and render process is the client which is not really trusted. Is there any reason as to why we are sending a de-activate event for a window with handle 0 ? If its null you should avoid the IPC call.

**Comment by mcatanzaro** [comment]
No, we're not hitting the check, it's just an issue I noticed by code inspection. In upstream Chromium [the GPU process is not trusted](http://www.chromium.org/Home/chromium-security/education/security-tips-for-ipc#TOC-Trust-only-the-browser-process..). (In fact, that's why it exists: to run risky WebGL in a separate process.) Given the architecture of Ozone-Wayland I'm not surprised that's not the case for us; if so this issue can be closed.

**Comment by kalyankondapally** [comment]
hmm no GPU process is the trusted process and is the only one allowed to issue any 3d system  calls (not only webgl). Render process is the untrusted process where the application code runs. The only difference in oz-wl architecture is that we receive inputs in GPU Process (adding an extra ipc call , but not sure sure how much extra ipc lag we have) which gets forwarded to Browser Process. It would be nice if we can receive them in Browser process directly, not sure if we can do that with current wayland protocol.

**Comment by mcatanzaro** [comment]
The upstream guidelines in the link above ("Do not trust renderer, PPAPI, or GPU processes") are pretty clear. :p I think the rationale behind the GPU process is that the 3D system calls are home to many security bugs.

**Comment by kalyankondapally** [comment]
Hmm interesting it does say that but not sure why. If you want to understand the benefits and overall architecture, this one is a good read https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome

The GPU process architecture offers several benefits including:

    Security: The bulk of the rendering logic remains in the sandboxed Renderer process, and access to platform 3D APIs is limited to only the GPU process.

    Robustness: A GPU process crash (e.g. due to faulty drivers) doesn't bring down the browser.

    Uniformity: Standardizing on OpenGL ES 2.0 as the rendering API for the browser regardless of the platform allows for a single, easier to maintain codebase across all OS ports of Chrome.

    Parallelism: The Renderer can quickly issue commands into the command buffer and go back to CPU-intensive rendering activities, leaving the GPU process to process them. We can make good use of both processes on multi-core machines as well as the GPU and CPU simultaneously thanks to this pipeline.

**Comment by kalyankondapally** [comment]
Btwn, these DCHECKS just help to track down this case if its ever to happen, we could replace it with an early return and a log message ?

**Comment by mcatanzaro** [comment]
That's a great article!

I agree that replacing the DCHECKs with early returns + log messages would be good.
