### ISSUE TITLE
Keyboard input is broken in Milestone-Trask

### ISSUE THREAD

**Issue by hobbitalastair** [01org/ozone-wayland#415]
It might just be me, but keyboard input seems to be broken in Milestone-Trask - for instance, I can click on the multibar and type, but nothing appears, and text fields appear to behave the same way.

My Milestone-Jefferson build seems to work just fine, though.

**Comment by hobbitalastair** [comment]
There's a whole bunch of errors in the output from Chromium, several times a second by the looks of it:

   [1525:1525:0825/160429:ERROR:xkb_keyboard_layout_engine.cc(826)] No current XKB state

Actually, there's quite a few other errors in the log as well... but this might be related?

**Comment by hobbitalastair** [comment]
Strangely, another run of Chromium (same build...) didn't have this problem, although I had managed to reproduce it just a minute before :frowning:

**Comment by clopez** [comment]
Same problem here.

I updated from ozone-wayland rev 00db18396b496303ee36b887e8ac69060dec9b76 to e94d887f9ca43bac422c5445939f824da7e1f599 and the keyboard stopped working.

Each time I press a key, this error appears on the shell:

    [687:687:0826/151735:ERROR:xkb_keyboard_layout_engine.cc(820)] No current XKB state

**Comment by kalyankondapally** [comment]
Looks like XKB initialization failed for some reason.  

@clopez Is it in random runs like @hobbitalastair  observed or its broken always for you ?

**Comment by clopez** [comment]
@kalyankondapally is always broken for me.

**Comment by kalyankondapally** [comment]
@clopez Just making sure, is XKB support enabled for weston on your env ? i.e. --disable-xkbcommon hasn't been passed while building it.

**Comment by michaelforney** [comment]
It is broken for me as well. I looked into it a little, and I think WaylandDisplay is receiving wl_keyboard.keymap and trying to dispatch the InitializeXKB event before the IPC channel is established. I get the error

    [13776:13780:0829/110835:WARNING:ipc_message_attachment_set.cc(53)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1

which indicates that InitializeXKB did not make it through to WindowManagerWayland::InitializeXKB.

**Comment by mcatanzaro** [comment]
I confirm; at the time `WaylandDisplay::InitializeXKB` is called, `WaylandDisplay::loop_` is null, so the message gets dropped.

**Comment by mcatanzaro** [comment]
Reverting 8d24dce89290b10362a5b5a82116a19e9e79e381 fixes that problem and the "No current XKB state" issue, but it does not fix keyboard input.

**Comment by kalyankondapally** [comment]
I have split the keyboard input here: https://github.com/01org/ozone-wayland/issues/416
This issue will deal with getting Sandboxing and XKB Initalization to work
