### ISSUE TITLE
Razzberry-C46

### ISSUE THREAD

**Issue by kalyankondapally** [01org/ozone-wayland#417]
Add:
1)Release notes.
2)Source release and test every thing works properly with appropriate Chromium release.

**Comment by kalyankondapally** [comment]
@rakuco  @joone @hobbitalastair @clopez @mcatanzaro 

Next release tracker.

**Comment by joone** [comment]
Done. https://github.com/01org/ozone-wayland/tree/Milestone-SouthSister
