### ISSUE TITLE
Lose the gtk2 dependency

### ISSUE THREAD

**Issue by strelec** [01org/ozone-wayland#418]
Does ozone-wayland run on Wayland (without XWayland), despite having gtk2 as dependency? As far as I know, gtk2 cannot properly run on wayland.

I would be great to have this in order for Gnome 3.18 release.

Here's the topic from arch linux forum:
https://bbs.archlinux.org/viewtopic.php?id=189455&p=2

**Comment by kalyankondapally** [comment]
We don't have any dependency on gtk2. GTK2 is used for dialogs, theming etc in Chrome, which we are missing. There is ongoing GTK3 work here https://code.google.com/p/chromium/issues/detail?id=132847 which we might want to leverage too.

**Comment by kalyankondapally** [comment]
I am closing this, feel free to re-open this in case you find any dependencies.
