### ISSUE TITLE
Errors getting when using two wl_display_connect in same process

### ISSUE THREAD

**Issue by madanagopalt** [01org/ozone-wayland#420]
Hi Team,

I am trying to run ozone wayland with one more qt application (i.e qt application running on qt wayland). When trying to post the output from chromium, we are getting below error:

libwayland: unknown object (19), message attach(?oii)
wl_display@1: error 1: invalid arguments for wl_surface@3.attach
display_poll_thread.cc(96)] wl_display_dispatch failed with an error.22

Qt window is displaying on wayland display. But, chromium output is not coming. Basically, i can see the problem is because the buffer objects registered with the client qt is clashing with the buffer objects registred by ozone wayland. So, it is telling buffer object passed from ozone wayland is invalid. Do anybody got the above error?. Thanks.

Regards,
Kannan

**Comment by kalyankondapally** [comment]
sorry, about the delay
I think you  have an ongoing discussion here:  http://lists.freedesktop.org/archives/wayland-devel/2015-September/024209.html ?

**Comment by kalyankondapally** [comment]
@madanagopalt I am closing this as we dont support nested compositor case.
