### ISSUE TITLE
Need help on shell display in weston

### ISSUE THREAD

**Issue by madanagopalt** [01org/ozone-wayland#423]
Hi Team,

I am using ozone wayland in my project.I am able to get the browser content displayed in weston server from ozone wayland.

I am using XDG shell. I need solutions for below two requirements:

1, Do we have any way to configure XDG shell, so that it has way to display output as layers (i.e hide behind the main screen).Such that, it will be displayed only  if i do hole punching in the top level window displayed from other weston connection.
2, In my output window in weston, i am seeing minimize and close option in title bar.Is it possible to provide display without title bar itself?. Please suggest a way to do it.

Please provide suggestions for above two requirements.Thanks.

Regards,
Madan

**Comment by kalyankondapally** [comment]
Ya, we have support for XDG_SHELL, you can check here (OZONE_WAYLAND_USE_XDG_SHELL should be set in your env): https://github.com/01org/ozone-wayland/blob/master/wayland/shell/shell.cc#L62

**Comment by kalyankondapally** [comment]
Reg 2: Do you want to show it in Fullscreen ?

**Comment by madanagopalt** [comment]
Hi,

Thanks.

1, We are using XDG shell, using the option you have shared. But is it
possible, to make it as a next layer of any top window seen in weston
compositor?. In my case, top level window can be any (say qt window), but
will be full screen.I will try to do hole punching in top window, so i can
see the layer below it (which is the output from ozone wayland) . So, i
need any configuration from ozone wayland, so it can be displayed as a
layer behind any top screen.

2, No, i don't wan't to show full screen. Also, XDG shell output is having
title title bar with close and minimize button. I don't want title bar
itself and no minimize and close button. Please let me know do we have any
ozone wayland configuration for that.

Thanks.

Regards,
Madan

On Fri, Sep 18, 2015 at 9:01 AM, kalyan kondapally <notifications@github.com

**Comment by kalyankondapally** [comment]
Hmm, I don't think 1) would be possible without a nested compositor setup.
2) We do have TYPE_WINDOW_FRAMELESS which you are looking for. We dont implement support for this yet. Not sure if crosswalk fits your use case beteer (Crosswalk is a web run time and uses ozone-wayland internally on wayland). @rakuco should be able to give input on this. Also, I haven't found a run time flag in chromium to create a frameless window. We have Embedded mode which actually would create a frame less window but that is a stripped down version of the browser.
