### ISSUE TITLE
ozone-wayland patch failed

### ISSUE THREAD

**Issue by mbinoy** [01org/ozone-wayland#432]
Hi

I have followed the same steps and tried to build this for a 64-bit Ubuntu 14.04 LTS desktop. 

Till the "gclient sync" things are fine, but applying the patches i am getting some error,

./src/ozone/patches/patch-chromium.sh 
Ozone-Wayland: patching Chromium
Switched to branch 'master'
Your branch is behind 'origin/master' by 31 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Deleted branch master-ozone (was 1c70d41).
Switched to a new branch 'master-ozone'
Applying: Browser: Support Desktop Aura creation on Ozone
Applying: Remove usage of DesktopFactory.
Applying: Add support to provide external ozone files in views.
Applying: Add support for checking DesktopWindow with Ozone and Ash.
Applying: Media: Build VaapiPictureWayland as part of Media.
Applying: Fix crash when switching to console(VT) mode
Applying: Add needed support in PlatformWindow.
Applying: Add file picker support using WebUI
Applying: Media: Use upstream Video Accelerator.
error: patch failed: chrome/browser/password_manager/password_store_factory.cc:61
error: chrome/browser/password_manager/password_store_factory.cc: patch does not apply
Patch failed at 0009 Media: Use upstream Video Accelerator.
The copy of the patch that failed is found in:
   /home/user/chromium_wayland/src/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

the below two patches i could see failed to install (others are applied)
1. 0009-Media-Use-upstream-Video-Accelerator.patch
2. 0011-Gardening-Adopt-to-https-codereview.chromium.org-129.patch

did anyone know about this, as suggested in the error log, doing a "git pull" will lead to different issues (may be it lead to a version which is not in sync)

doing a "gclient sync" after the above operations gives the below error

1> ____ src/ozone at refs/remotes/origin/master
1> 	You have unstaged changes.

**Comment by mbinoy** [comment]
and after skipping the 2 patches, trying to build chromium shows below

ninja: Entering directory `out/Debug'
ninja: error: '../../third_party/libvpx_new/source/libvpx/vpx_dsp/x86/quantize_avx_x86_64.asm', needed by 'gen/third_party/libvpx_new/quantize_avx_x86_64.o', missing and no known rule to make it

**Comment by kalyankondapally** [comment]
can you make sure you are on master branch before running ./src/ozone/patches/patch-chromium.sh

**Comment by mbinoy** [comment]
Hi Kalyan,

thanks for replying,

i just retried everything from scratch,

after the "gclient sync" is successfully completed, "git status" from "/src" folder says the git repo is in a "detached HEAD" state. so i did a "git checkout master" and tried applying the patches and ended up in the same error.

./src/ozone/patches/patch-chromium.sh 
Ozone-Wayland: patching Chromium
Switched to branch 'master'
Your branch is behind 'origin/master' by 64 commits, and can be fast-forwarded.
(use "git pull" to update your local branch)
Deleted branch master-ozone (was 1c70d41).
Switched to a new branch 'master-ozone'
Applying: Browser: Support Desktop Aura creation on Ozone
Applying: Remove usage of DesktopFactory.
Applying: Add support to provide external ozone files in views.
Applying: Add support for checking DesktopWindow with Ozone and Ash.
Applying: Media: Build VaapiPictureWayland as part of Media.
Applying: Fix crash when switching to console(VT) mode
Applying: Add needed support in PlatformWindow.
Applying: Add file picker support using WebUI
Applying: Media: Use upstream Video Accelerator.
error: patch failed: chrome/browser/password_manager/password_store_factory.cc:61
error: chrome/browser/password_manager/password_store_factory.cc: patch does not apply
Patch failed at 0009 Media: Use upstream Video Accelerator.

again, tired to do "git pull" and apply patch, but faced the same issue.

**Comment by kalyankondapally** [comment]
can you do gclient sync after checking out master branch, also make sure your git revision is same as chromium_rev here : https://github.com/01org/ozone-wayland/blob/master/.DEPS.git

**Comment by mbinoy** [comment]
yes thanks, there it got missed, somehow my revision is different from what you given (may be an unwanted "git pull" send me somewhere else)

i just did a reset hard, and checked the revision (cat .git/refs/heads/master) and we are aligned.

now applying the patch also successful. Let me proceed with building and exploring this wonderful project.

Thanks a lot for your kind support.
