### ISSUE TITLE
error: cannot find -lxkbcommon

### ISSUE THREAD

**Issue by vrotenberg** [01org/ozone-wayland#445]
Hello!
While compilation by ninja -C out/Debug -j16 chrome I always get the error:
The comnmand ./build/install-build-deps.sh successful.
What is wrong?
Thanks,

**Comment by vrotenberg** [comment]
The error is "src/third_party/binutils/Linux_x64/Release/bin/ld: error: cannot find -lxkbcommon"

**Comment by vrotenberg** [comment]
Please please help! The building is almost done! It's strange that the ld cannot find the library that exists. Where does it search for it?

**Comment by vrotenberg** [comment]
The last lines I have are:
obj/base/allocator/liballocator.a -Wl,--end-group  -lrt -ldl -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lfontconfig -lfreetype -lpangocairo-1.0 -lcairo -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lresolv -lgmodule-2.0 -lgthread-2.0 -lxkbcommon -lasound -lm -lz -ldbus-1 -lexpat

**Comment by vrotenberg** [comment]
The problem was because the compiler searches for the libraries in path-to-project/chromium/src/build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu
So..
cp /var/lib/chroot/trusty32bit/usr/lib/i386-linux-gnu/libxkbcommon.so.0.0.0  path-to-project/chromium/src/build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu and creating link libxkbcommon.so in the path-to-project/chromium/src/build/linux/debian_wheezy_i386-sysroot/usr/lib/i386-linux-gnu/ to the file libxkbcommon.so.0.0.0 solved the problem!

**Comment by rakuco** [comment]
That's because you were using the Debian Wheezy chroot that's on by default. If you pass `use_sysroot=0` the build should pick up your system libraries.
