### ISSUE TITLE
"Invalid file descriptor to ICU data received"

### ISSUE THREAD

**Issue by vrotenberg** [01org/ozone-wayland#447]
Hi!
At least I could build the chromium for wayland! But now when I am trying to run it I get the error:
"Invalid file descriptor to ICU data received"
What can I do now? So many work and time but still cannot run the project! Please help!

**Comment by vrotenberg** [comment]
Doesn't meter, I run it with http://www.google.com but now I have another error. Sorry.

**Comment by malakodas** [comment]
Hey how did you fix your "Invalid file descriptor to ICU data received" error?
