### ISSUE TITLE
OnKeyPress event not handled properly

### ISSUE THREAD

**Issue by jbrianceau** [01org/ozone-wayland#453]
The "Gardening: Adapt to https://codereview.chromium.org/1236923003"
commit (25315fc81890a54e49ea357b4ed0391eff868eb6) seems incomplete.
According to what has been done in desktop_window_tree_host_x11.cc,
we need to stop event propagation and we do not have to call
SendEventToProcessor.

The following test page can be used to monitor OnKeyPress event:
http://www.asquare.net/javascript/tests/KeyCode.html

**Comment by jbrianceau** [comment]
Fix proposal : https://github.com/jbrianceau/ozone-wayland/commit/ec897cd2e98722aa143166ff36c214214a238149

**Comment by joone** [comment]
@jbrianceau  I will take a look at your patch. Thank you.

**Comment by jbrianceau** [comment]
@joone Thanks ! FYI, I just saw that this issue and https://github.com/01org/ozone-wayland/issues/419 are related.

**Comment by jbrianceau** [comment]
@joone: any update? Did you find time to take a look at my patch ?

**Comment by jbrianceau** [comment]
Change fixed following @joone comments (and rebased on top of master branch) available here : https://github.com/jbrianceau/ozone-wayland/commit/7cf1e955a64df6eac792800f0d29a71119227967

**Comment by jbrianceau** [comment]
Merged in master branch : https://github.com/01org/ozone-wayland/commit/607abb6913f761e3cb7dfccfd72e30173e4bc4ea
Closing issue.
