### ISSUE TITLE
multi screen support in ozone wayland

### ISSUE THREAD

**Issue by mbinoy** [01org/ozone-wayland#468]
Hi 

https://github.com/01org/ozone-wayland/blob/master/wayland/display.cc#L622
The above says the multi screen support is not added, is any one started supporting this? Or any plans on this implementation, kindly let us know.

**Comment by jhagberg** [comment]
Yes will that add support for changing scaling when moving between screens with different DPI? This works great when running Gnome on Wayland.

**Comment by nickmessing** [comment]
@jhagberg, you said it works great on gnome on wayland, is it a part of `google-chrome-stable`? It doesn't work for me.

**Comment by jhagberg** [comment]
Sorry if I am unclear. I mean that the Gnome apps like file browser and such works very good. It scales depending on what screen the app is moved to.

**Comment by nickmessing** [comment]
@jhagberg, oh, is there any web-browser based on Webkit/Blink that supports that atm or we are stuck with not working properly chrome and ff?

**Comment by jhagberg** [comment]
I have not seen anything yet. My workaround at the moment is running chrome on the laptop and chromium on the other screens. If you set the primary screen to the external monitor after you start chrome on the laptop it will have another scaling. I will investigate more

**Comment by nickmessing** [comment]
@jhagberg, I'm using `fish` shell and I use this as a workaround:
```
function chrome
    set -lx WAYLAND_DISPLAY wayland-1
    google-chrome-stable -high-dpi-support=1 -force-device-scale-factor=1
end
```
Basically if you run `chrome` from terminal it's on external screen, if it's just by "click" it's on main screen :)

**Comment by jhagberg** [comment]
aha. Can you have two versions of chrome running? I cant get this to work in bash when I already have a instance of Chrome on  HDPI laptop display.

**Comment by nickmessing** [comment]
@jhagberg, Unfortunately no, I use stable and beta for that :)

**Comment by jaragunde** [comment]
I've been able to use Ozone-Wayland in a multi-screen setup on the GENIVI Platform. It features the Wayland IVI extensions, which let a controller application define regions in any available screens and assign surfaces to them. In this scenario, applications aren't aware of the actual screens and don't deal with them directly, that's why it works despite this open issue.

**Comment by mbinoy** [comment]
@jaragunde yes, same experienced in my side, but what missing currently is multi seat handling, getting the touch working at the same time for both the windows is not handled at the moment. probably this leads to adding multiple screen / seat supported in ozone wayland.

**Comment by jaragunde** [comment]
@mbinoy right, it's currently not possible to e.g. assign different seats to different browser windows. We are currently trying to address that scenario to include Chromium in the next release of GENIVI.

**Comment by mbinoy** [comment]
provided an excellent reference from @jaragunde here!
https://blogs.igalia.com/jaragunde/2017/06/16/genivi-fying-chromium-part-3-multi-seat/#more-754
